name: btrpc
description: BTRPC Dart Client.
version: 1.0.0
homepage: https://gitlab.zhulinkeji.com/middleware/rpc-dart-client

environment:
  sdk: ">=3.0.0 <4.0.0"

  
dependencies: 
  grpc: ^3.2.3
  protobuf: ^3.0.0


dev_dependencies:
  test: ^1.16.3
  pedantic: ">=1.10.0"
  json_annotation: ^4.8.1
  json_serializable: ^6.1.3
  build_runner: ^2.1.7
